/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenii_josehernandez;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author jrdjh
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);
        adminUsuarios admin = new adminUsuarios("./usuarios.hc");
        adminCanales adminC = new adminCanales("./canales.hc");
        admin.cargarArchivo();
        adminC.cargarArchivo();
        DefaultComboBoxModel cbModel = (DefaultComboBoxModel) cb_categorias.getModel();
        cbModel.addElement("Juegos");
        cbModel.addElement("Entretenimiento");
        cbModel.addElement("Deporte");
        cbModel.addElement("Cocina");
        cbModel.addElement("Salud");
        cb_categorias.setModel(cbModel);

        DefaultTableModel model = (DefaultTableModel) jt_canales.getModel();
        jt_canales.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Categoria", "Suscriptores"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        for (int i = 0; i < adminC.getLista_canales().size(); i++) {
            Object[] newRow = {
                adminC.getLista_canales().get(i).getNombre(), adminC.getLista_canales().get(i).getCategoria(),
                adminC.getLista_canales().get(i).getNum_suscriptores()
            };
            model.addRow(newRow);
        }
        jt_canales.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registrar = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        tf_nombreRegistro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sp_edad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        tf_correoRegistro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_nombreCanal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_usuarioRegistrar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pf_contrasenaRegistro = new javax.swing.JPasswordField();
        cb_categorias = new javax.swing.JComboBox<>();
        jd_cuenta = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_canales = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtree_categorias = new javax.swing.JTree();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tf_nombreVideo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sp_duracionVideo = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_subtitulos = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_video = new javax.swing.JTable();
        pop_reproduccion = new javax.swing.JPopupMenu();
        jm_repro = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tf_usuarioLog = new javax.swing.JTextField();
        pf_pass = new javax.swing.JPasswordField();

        jLabel4.setText("Nombre:");

        jLabel5.setText("Edad:");

        jLabel6.setText("Correo:");

        jLabel7.setText("Nombre del Canal:");

        jLabel8.setText("Usuario:");

        jLabel9.setText("Categoria del Canal:");

        jButton3.setText("Crear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Registrar");

        jLabel11.setText("Contraseña:");

        javax.swing.GroupLayout RegistrarLayout = new javax.swing.GroupLayout(Registrar.getContentPane());
        Registrar.getContentPane().setLayout(RegistrarLayout);
        RegistrarLayout.setHorizontalGroup(
            RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(155, 155, 155))
            .addGroup(RegistrarLayout.createSequentialGroup()
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(RegistrarLayout.createSequentialGroup()
                                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombreRegistro)
                                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_correoRegistro)
                                    .addComponent(tf_usuarioRegistrar)
                                    .addComponent(pf_contrasenaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                .addGap(80, 80, 80)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreCanal)
                            .addComponent(cb_categorias, 0, 115, Short.MAX_VALUE)))
                    .addGroup(RegistrarLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel10)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        RegistrarLayout.setVerticalGroup(
            RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(67, 67, 67)
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombreCanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_correoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_usuarioRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pf_contrasenaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        jt_canales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Categoria", "Suscriptores"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_canales);

        jButton4.setText("Suscribirme");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Canales", jPanel1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categorias");
        jtree_categorias.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree_categorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree_categoriasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtree_categorias);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Canales Suscritos", jPanel2);

        jLabel12.setText("Nombre:");

        jLabel13.setText("Tiempo de Duracion:");

        jLabel14.setText("Subtitulos:");

        ta_subtitulos.setColumns(20);
        ta_subtitulos.setRows(5);
        jScrollPane3.setViewportView(ta_subtitulos);

        jButton5.setText("Crear Video");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nombreVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_duracionVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(320, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(104, 104, 104))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_nombreVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sp_duracionVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jButton5)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Video", jPanel3);

        jt_video.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tiemp.Duracion", "N°Likes", "Comentarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jt_video);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Videos de Mi Canal", jPanel4);

        javax.swing.GroupLayout jd_cuentaLayout = new javax.swing.GroupLayout(jd_cuenta.getContentPane());
        jd_cuenta.getContentPane().setLayout(jd_cuentaLayout);
        jd_cuentaLayout.setHorizontalGroup(
            jd_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jd_cuentaLayout.setVerticalGroup(
            jd_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jm_repro.setText("Reproducir");
        pop_reproduccion.add(jm_repro);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LOGIN");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Contraseña:");

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Registrar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_usuarioLog)
                            .addComponent(pf_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButton1)
                        .addGap(108, 108, 108)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_usuarioLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setVisible(false);
        Registrar.pack();
        Registrar.setModal(true);
        Registrar.setLocationRelativeTo(this);
        Registrar.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        adminUsuarios admin = new adminUsuarios("./usuarios.hc");
        adminCanales adminC = new adminCanales("./canales.hc");
        admin.cargarArchivo();
        adminC.cargarArchivo();
        Canal temp;
        String nombre = tf_nombreRegistro.getText();

        int edad = (int) sp_edad.getValue();
        String correo = tf_correoRegistro.getText();
        String usuarioR = tf_usuarioRegistrar.getText();
        String contraR = pf_contrasenaRegistro.getText();

        String nombreCanal = tf_nombreCanal.getText();
        String categoriaCanal = (String) cb_categorias.getSelectedItem();

        temp = new Canal(nombreCanal, categoriaCanal);
        Usuario temporal = new Usuario(nombre, edad, correo, usuarioR, temp, contraR);
        admin.getLista_usuarios().add(temporal);
        adminC.getLista_canales().add(temp);
        adminC.escribirArchivo();
        admin.escribirArchivo();
        tf_nombreRegistro.setText("");
        sp_edad.setValue(0);
        tf_correoRegistro.setText("");
        tf_usuarioRegistrar.setText("");
        pf_contrasenaRegistro.setText("");
        tf_nombreCanal.setText("");

        Registrar.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categorias");
        jtree_categorias.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));

        jScrollPane2.setViewportView(jtree_categorias);
        DefaultTreeModel modelArbol = (DefaultTreeModel) jtree_categorias.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelArbol.getRoot();

        DefaultMutableTreeNode juegos = new DefaultMutableTreeNode("Juegos");
        raiz.add(juegos);
        DefaultMutableTreeNode entre = new DefaultMutableTreeNode("Entretenimiento");
        raiz.add(entre);
        DefaultMutableTreeNode salud = new DefaultMutableTreeNode("Salud");
        raiz.add(salud);
        DefaultMutableTreeNode dep = new DefaultMutableTreeNode("Deportes");
        raiz.add(dep);
        DefaultMutableTreeNode cocina = new DefaultMutableTreeNode("Cocina");
        raiz.add(cocina);
        modelArbol.reload();
        adminUsuarios admin = new adminUsuarios("./usuarios.hc");
        adminCanales adminC = new adminCanales("./canales.hc");
        admin.cargarArchivo();
        adminC.cargarArchivo();

        usuarioPrincipal = tf_usuarioLog.getText();
        contraPrincipal = pf_pass.getText();
        jt_canales.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Categoria", "Suscriptores"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        //cargar los canales
        DefaultTableModel m = (DefaultTableModel) jt_canales.getModel();

        for (int i = 0; i < adminC.getLista_canales().size(); i++) {
            Object[] row = {
                adminC.getLista_canales().get(i).getNombre(), adminC.getLista_canales().get(i).getCategoria(),
                adminC.getLista_canales().get(i).getNum_suscriptores()
            };
            m.addRow(row);

        }

        jt_canales.setModel(m);

        for (int i = 0; i < admin.getLista_usuarios().size(); i++) {
            if (usuarioPrincipal.equals(admin.getLista_usuarios().get(i).getNom_usuario())
                    && contraPrincipal.equals(admin.getLista_usuarios().get(i).getContrasena())) {
                usuario_actual = admin.getLista_usuarios().get(i);

                this.setVisible(false);
                jd_cuenta.pack();
                jd_cuenta.setModal(true);
                jd_cuenta.setLocationRelativeTo(this);
                jd_cuenta.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if (sus == 1) {

        } else {
            javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categorias");
            jtree_categorias.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
            jScrollPane2.setViewportView(jtree_categorias);
            modelArbol = (DefaultTreeModel) jtree_categorias.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelArbol.getRoot();

            juegos = new DefaultMutableTreeNode("Juegos");
            raiz.add(juegos);
            entre = new DefaultMutableTreeNode("Entretenimiento");
            raiz.add(entre);
            salud = new DefaultMutableTreeNode("Salud");
            raiz.add(salud);
            dep = new DefaultMutableTreeNode("Deportes");
            raiz.add(dep);
            cocina = new DefaultMutableTreeNode("Cocina");
            raiz.add(cocina);
            modelArbol.reload();
            sus++;
        }

        adminUsuarios admin = new adminUsuarios("./usuarios.hc");
        adminCanales adminC = new adminCanales("./canales.hc");
        admin.cargarArchivo();
        adminC.cargarArchivo();
        Canal tempAñadir;
        DefaultTableModel modell = (DefaultTableModel) jt_canales.getModel();

        if (jt_canales.getSelectedRow() >= 0) {
            int index = jt_canales.getSelectedRow();

            tempAñadir = adminC.getLista_canales().get(jt_canales.getSelectedRow());
            usuario_actual.getCanales_suscritos().add(tempAñadir);
            for (int i = 0; i < admin.getLista_usuarios().size(); i++) {
                if (usuario_actual.getNom_usuario().equals(admin.getLista_usuarios().get(i).getNom_usuario())
                        && usuario_actual.getContrasena().equals(admin.getLista_usuarios().get(i).getContrasena())) {
                    admin.getLista_usuarios().get(i).getCanales_suscritos().add(tempAñadir);
                    admin.escribirArchivo();
                    JOptionPane.showMessageDialog(jd_cuenta, "Suscrito");

                }
            }
            for (int i = 0; i < adminC.getLista_canales().size(); i++) {
                if (adminC.getLista_canales().get(index).getCategoria().toString().equals("Juegos")) {
                    DefaultMutableTreeNode nombreCanal = new DefaultMutableTreeNode(adminC.getLista_canales().get(index));
                    for (int j = 0; j < adminC.getLista_canales().get(index).getVideos_propios().size(); j++) {
                        DefaultMutableTreeNode video = new DefaultMutableTreeNode(adminC.getLista_canales().get(index).getVideos_propios().get(j).toString());
                        nombreCanal.add(video);
                    }
                    juegos.add(nombreCanal);
                    break;

                } else if (adminC.getLista_canales().get(index).getCategoria().toString().equals("Entretenimiento")) {
                    DefaultMutableTreeNode nombreCanal = new DefaultMutableTreeNode(adminC.getLista_canales().get(index));
                    for (int j = 0; j < adminC.getLista_canales().get(index).getVideos_propios().size(); j++) {
                        DefaultMutableTreeNode video = new DefaultMutableTreeNode(adminC.getLista_canales().get(index).getVideos_propios().get(j).toString());
                        nombreCanal.add(video);
                    }
                    entre.add(nombreCanal);
                    break;
                } else if (adminC.getLista_canales().get(index).getCategoria().toString().equals("Salud")) {
                    DefaultMutableTreeNode nombreCanal = new DefaultMutableTreeNode(adminC.getLista_canales().get(index));
                    for (int j = 0; j < adminC.getLista_canales().get(index).getVideos_propios().size(); j++) {
                        DefaultMutableTreeNode video = new DefaultMutableTreeNode(adminC.getLista_canales().get(index).getVideos_propios().get(j).toString());
                        nombreCanal.add(video);
                    }
                    salud.add(nombreCanal);
                    break;
                } else if (adminC.getLista_canales().get(index).getCategoria().toString().equals("Deportes")) {
                    DefaultMutableTreeNode nombreCanal = new DefaultMutableTreeNode(adminC.getLista_canales().get(index));
                    for (int j = 0; j < adminC.getLista_canales().get(index).getVideos_propios().size(); j++) {
                        DefaultMutableTreeNode video = new DefaultMutableTreeNode(adminC.getLista_canales().get(index).getVideos_propios().get(j).toString());
                        nombreCanal.add(video);
                    }
                    dep.add(nombreCanal);
                    break;
                } else if (adminC.getLista_canales().get(index).getCategoria().toString().equals("Cocina")) {
                    DefaultMutableTreeNode nombreCanal = new DefaultMutableTreeNode(adminC.getLista_canales().get(index));
                    for (int j = 0; j < adminC.getLista_canales().get(index).getVideos_propios().size(); j++) {
                        DefaultMutableTreeNode video = new DefaultMutableTreeNode(adminC.getLista_canales().get(index).getVideos_propios().get(j).toString());
                        nombreCanal.add(video);
                    }
                    cocina.add(nombreCanal);
                    break;
                }
            }
            modell.removeRow(jt_canales.getSelectedRow());
            jt_canales.setModel(modell);

            modelArbol.reload();
//            
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        //
        adminUsuarios admin = new adminUsuarios("./usuarios.hc");
        adminCanales adminC = new adminCanales("./canales.hc");
        adminC.cargarArchivo();
        admin.cargarArchivo();
        String nombreVideo = tf_nombreVideo.getText();
        String subtitulos = ta_subtitulos.getText();
        int duracion = (int) sp_duracionVideo.getValue();
        jt_video.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Tiemp.Duracion", "N°Likes", "Comentarios"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        for (int i = 0; i < admin.getLista_usuarios().size(); i++) {
            if (usuarioPrincipal.equals(admin.getLista_usuarios().get(i).getNom_usuario())
                    && contraPrincipal.equals(admin.getLista_usuarios().get(i).getContrasena())) {
                Video newVideo = new Video(nombreVideo, duracion, subtitulos);

                usuario_actual.getCanal().getVideos_propios().add(newVideo);
                admin.getLista_usuarios().get(i).getCanal().getVideos_propios().add(newVideo);
                admin.escribirArchivo();

            }

        }
        DefaultTableModel Tmodel = (DefaultTableModel) jt_video.getModel();
        for (int i = 0; i < usuario_actual.getCanal().getVideos_propios().size(); i++) {
            Object[] rowRow = {
                usuario_actual.getCanal().getVideos_propios().get(i).getNombre(),
                usuario_actual.getCanal().getVideos_propios().get(i).getTiempo_duracion(),
                usuario_actual.getCanal().getVideos_propios().get(i).getNum_likes(),
                usuario_actual.getCanal().getVideos_propios().get(i).getComentarios()

            };
            Tmodel.addRow(rowRow);
        }
        jt_video.setModel(Tmodel);

        tf_nombreVideo.setText("");
        ta_subtitulos.setText("");
        sp_duracionVideo.setValue(0);


    }//GEN-LAST:event_jButton5MouseClicked

    private void jtree_categoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree_categoriasMouseClicked
        if (evt.isMetaDown()) {
            int row = jtree_categorias.getClosestRowForLocation(evt.getX(), evt.getY());
            jtree_categorias.setSelectionRow(row);
            Object v1 = jtree_categorias.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            pop_reproduccion.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jtree_categoriasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Registrar;
    private javax.swing.JComboBox<String> cb_categorias;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jd_cuenta;
    private javax.swing.JMenuItem jm_repro;
    private javax.swing.JTable jt_canales;
    private javax.swing.JTable jt_video;
    private javax.swing.JTree jtree_categorias;
    private javax.swing.JPasswordField pf_contrasenaRegistro;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JPopupMenu pop_reproduccion;
    private javax.swing.JSpinner sp_duracionVideo;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTextArea ta_subtitulos;
    private javax.swing.JTextField tf_correoRegistro;
    private javax.swing.JTextField tf_nombreCanal;
    private javax.swing.JTextField tf_nombreRegistro;
    private javax.swing.JTextField tf_nombreVideo;
    private javax.swing.JTextField tf_usuarioLog;
    private javax.swing.JTextField tf_usuarioRegistrar;
    // End of variables declaration//GEN-END:variables
    Usuario usuario_actual;
    String usuarioPrincipal;
    String contraPrincipal;
    DefaultMutableTreeNode nodo_seleccionado;
    DefaultMutableTreeNode juegos;
    DefaultMutableTreeNode entre;
    DefaultMutableTreeNode salud;
    DefaultMutableTreeNode dep;
    DefaultMutableTreeNode cocina;
    DefaultTreeModel modelArbol;
    int sus = 0;
}
